In [13]:
import pandas as pd

# Load dataset
df = pd.read_csv("students.csv")
print(f"Dataset loaded.")

Dataset loaded.

In [14]:
# Check structure and missing values
df.info()

print("\nMissing values:")
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           20 non-null     str
 1   Department     20 non-null     str
 2   Age            20 non-null     int64
 3   Gender         20 non-null     str
 4   Marks          19 non-null     float64
 5   Attendance(%)  20 non-null     int64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.1 KB

Missing values:
Name             0
Department       0
Age              0
Gender           0
Marks            1
Attendance(%)    0
dtype: int64

In [15]:
# Fill missing marks with mean value
mean_marks = df["Marks"].mean()
df["Marks"] = df["Marks"].fillna(mean_marks)

print(f"Missing values filled with mean: {round(mean_marks, 1)}")

df

Missing values filled with mean: 84.0

      Name Department  Age Gender  Marks  Attendance(%)
0   Manish         IT   21      M   85.0             92
1     Sita         IT   20      F   90.0             95
2      Ram        BCA   22      M   78.0             88
3     Hari        BCA   21      M   84.0             80
4     Gita       CSIT   20      F   88.0             94
5    Nabin         IT   22      M   95.0             97
6    Priya       CSIT   21      F   82.0             89
7    Kiran        BCA   20      M   76.0             85
8    Anita         IT   21      F   91.0             96
9    Rohit       CSIT   22      M   89.0             90
10   Aarav         IT   20      M   73.0             75
11    Asha        BCA   21      F   84.0             87
12   Binod       CSIT   22      M   79.0             83
13  Sunita         IT   20      F   92.0             98
14   Sagar        BCA   23      M   81.0             86
15    Maya       CSIT   21      F   87.0             91
16   Dipak         IT   22      M   69.0             72
17   Laxmi        BCA   20      F   94.0             99
18    Anil       CSIT   21      M   77.0             80
19   Pooja         IT   20      F   86.0             93

In [16]:
# Students scoring above 90
top_students = df[df["Marks"] > 90]

print(f"Top students count: {len(top_students)}")
top_students

Top students count: 4

      Name Department  Age Gender  Marks  Attendance(%)
5    Nabin         IT   22      M   95.0             97
8    Anita         IT   21      F   91.0             96
13  Sunita         IT   20      F   92.0             98
17   Laxmi        BCA   20      F   94.0             99

In [9]:
# Department-wise average marks
dept_summary = df.groupby("Department")["Marks"].mean().round(1).reset_index()

print("Department-wise average marks:")
dept_summary

Department-wise average marks:

  Department  Marks
0        BCA   82.8
1       CSIT   83.7
2         IT   85.1

In [10]:
# Overall statistics
df["Marks"].describe().round(1)

count    20.0
mean     84.0
std       7.1
min      69.0
25%      78.8
50%      84.5
75%      89.2
max      95.0
Name: Marks, dtype: float64